### ISSUE TITLE
Not working anymore :(

### ISSUE THREAD

**Issue by rubenvde** [zaddev/BattleShipCSharp#1]
Socket IO Client is te oud om het spel te spelen. Geeft een connection is closed.

**Comment by CvdH** [comment]
Op mijn machine getest samen met  @rubenvde , zie hier de exception tekst:

`System.Exception: Connection has closed 
at ZeeslagLib.Game.BattleShipSettings_OnConnectionURLChange(Object sender, EventArgs e) in C:\Users\caspe\Downloads\BattleShipCSharp-master\ZeeslagLib\Game.cs:line 29
   at ZeeslagLib.BattleShipSettings.set_ConnectionURL(String value) in C:\Users\caspe\Downloads\BattleShipCSharp-master\ZeeslagLib\BattleShipSettings.cs:line 36
   at ZeeslagForm.SettingsScreen.buttonConfirm_Click(Object sender, EventArgs e) in C:\Users\caspe\Downloads\BattleShipCSharp-master\ZeeslagForm\SettingsScreen.cs:line 25
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)`

**Comment by barld** [comment]
![image](https://user-images.githubusercontent.com/2761172/33509319-b1b69168-d700-11e7-97a8-aaa9ff6bea1d.png)

Hier doet hij het nog. Maar of hij altijd stabiel is durf ik niet te garanderen. Maar willen jullie je hier echt nog bezig gaan houden. Ik wens jullie in ieder geval veel plezier

**Comment by barld** [comment]
@CvdH  Ik weet niet of @rubenvde ook rechten kan uitdelen op deze repo maar anders kan ik je zo rechten geven als je dat wilt
